# -*- coding: utf-8 -*-
"""ModernHW3Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NO4SwqrCRvaASQRPHwl5MB2icVfhULI1
"""

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.patches as mpatches

lamb = .00000067
c = 299792458
omeg = (2*np.pi*c)/lamb
eps = np.pi/2
z = 0
k = 1
E_0x = 125
E_0y = 125

t = np.linspace(0, 4*np.pi/omeg, 100000)

E_x = E_0x*np.cos(omeg*t-k*z+eps)
E_y = E_0y*np.cos(omeg*t-k*z)

fig, ax = plt.subplots()
ax.plot(t, E_x, color = 'blue')
ax.plot(t, E_y, color = 'red')

ax.set(xlabel='t (sec)', ylabel='E(0, t)', title='E Wave Propogation (e = pi/2)')
red = mpatches.Patch(color='blue', label='X')
blue = mpatches.Patch(color='red', label='Y')
plt.legend(handles=[red,blue])

plt.show()

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.patches as mpatches

lamb = .00000067
c = 299792458
omeg = (2*np.pi*c)/lamb
eps = np.pi/2
z = 0
k = 1
E_0x = 125
E_0y = 125

t = np.linspace(0, 4*np.pi/omeg, 100000)

E_x = E_0x*np.cos(omeg*t-k*z+eps)
E_y = E_0y*np.cos(omeg*t-k*z)

fig, ax = plt.subplots()
ax.plot(E_x, E_y)

ax.set(xlabel='Ex(t)', ylabel='Ey(t)', title='E Wave Parameterization (e = pi/2)')

plt.show()